### ISSUE TITLE
Running the plugin as a standalone executable throws Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by dprogm** [smnbbrv/ngx-grpc#104]
When using the plugin without any other dependency it throws the following error:

```
node:internal/modules/cjs/loader:1073
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- /Users/workstation/Dev/test_grpc/node_modules/@ngx-grpc/protoc-gen-ng/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/Users/workstation/Dev/test_grpc/node_modules/@ngx-grpc/protoc-gen-ng/main.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/workstation/Dev/test_grpc/node_modules/@ngx-grpc/protoc-gen-ng/main.js'
  ]
}

Node.js v20.3.0
```

**Steps to reproduce:**
Add a package.json with the following content:
```json
{
  "devDependencies": {
    "@ngx-grpc/protoc-gen-ng": "^3.1.1"
  },
  "scripts": {
    "proto:generate": "protoc-gen-ng"
  }
}
```
Run from the root directory:
```bash
npm install
npm run proto:generate
```
**Possible solution:**
Add `tslib` as a dependency for package `@ngx-grpc/protoc-gen-ng`

**Comment by smnbbrv** [comment]
Hi, is that a real use-case scenario? Normally you would already have angular with all of its dependencies in place

This however should be fixed

**Comment by dprogm** [comment]
Hello @smnbbrv,

I agree with you, this is not a usual use-case. However I am using the plugin in a bazel build which forces us to add this dependency explicitly because it is not a direct/implicit dependency of the plugin itself. Therefore this is just "nice to have" to have this fixed upstream. :wink:

**Comment by smnbbrv** [comment]
I'm totally fine with this. Could you, please, prepare a PR with the dep?

**Comment by dprogm** [comment]
Sure, I am going to prepare a PR.

**Comment by dprogm** [comment]
**Update: I was trying to reproduce this with a local setup.**

1) Clone this repository from latest commit
2) `npm ci`
3) `npm run build:lib:protoc-gen-ng`
4) Create a folder locally with an empty `package.json`
5) `npm install -D /path/to/ngx-grpc/dist/protoc-gen-ng`
6) `npx protoc-gen-ng`

**Result: No error!**

If I am using the latest release `3.1.1` from npm the mentioned error is thrown.

**Comment by smnbbrv** [comment]
> Should all (sub-)packages list their dependencies explicitly?

of course, the root package.json is not anyhow getting into resulting published packages

**Comment by dprogm** [comment]
Okay, thanks. Then I am preparing a fix for it.
