### ISSUE TITLE
Question regarding google.api.http

### ISSUE THREAD

**Issue by Gluchito** [smnbbrv/ngx-grpc#107]
Is it possible for the http client to send a request to the address defined in the google.api.http option?

Thank you.

<img width="629" alt="image" src="https://github.com/smnbbrv/ngx-grpc/assets/16447121/09df9f59-6a82-42c7-8aca-960b568f43cf">

**Comment by smnbbrv** [comment]
hi @Gluchito 

the google.http.api is not meant for gRPC, it is meant for transcoding grpc to kinda http rest api. 

https://cloud.google.com/endpoints/docs/grpc/transcoding
